teleop:
  ros__parameters:
    joy_topic: /joy
    twist_topic: /cmd_vel
    move:
      forward:
        axis: 1
        scalse: 0.5
        deadzone: 0.0
      reverse:
        axis: 1
        scalse: 0.5
        deadzone: 0.0
      left:
        axis: 0
        scalse: 0.5
        deadzone: 0.0
      right:
        axis: 0
        scale: 1.5
        deadzone: 0.0
    turn:
      left:
        axis: 3
        scalse: 0.5
        deadzone: 0.0
        # offset: 1.0
      right:
        axis: 3
        scale: 0.5
        deadzone: 0.0
        # offset: 1.0

joystick:
  ros__parameters:
    joy_topic: /joy
    dev: /dev/input/js1
    deadzone: 0.2
