<?xml version="1.0"?>
<robot xmlns="http://www.ros.org" name="robot"
	xmlns:xacro="http://www.ros.org/wiki/xacro">
	<!-- Robot Size -->
	<xacro:property name="body_length" value="0.80" />
	<xacro:property name="body_with" value="0.5"/>
	<xacro:property name="body_heigth" value="0.20"/>
	<xacro:property name="wheel_height" value="0.087" />

	<!-- Wheel parameters -->
	<xacro:property name="wheel_offset_x" value="0.25" />
	<!-- x,y,z in translation from base_link to the center of the wheel -->
	<xacro:property name="wheel_offset_y" value="${(body_with/2+0.051)}" />
	<xacro:property name="wheel_offset_z" value="0.0" />
	<xacro:property name="wheel_radius" value="0.127" />
	<xacro:property name="update_rate" value="20" />

	<!-- BASE FOOTPRINT -->
	<link name="base_footprint">
		<must_be_base_link>true</must_be_base_link>
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size="0.001 0.001 0.001" />
			</geometry>
		</visual>
	</link>
	<xacro:include filename="core/material.xacro" />
	<xacro:materials />
	<xacro:include filename="core/omni_wheel.urdf.xacro" />
	<xacro:include filename="core/robot_body.urdf.xacro" />
	<xacro:include filename="core/follow_me_robot.gazebo.xacro" />

	<!-- Additional params -->
	<xacro:robot_body wheel_radius="${wheel_radius}" body_length="${body_length}" body_with="${body_with}" body_heigth="${body_heigth}" />

	<xacro:wheel_motor parent="robot_body_link" position="front" side="right" reflect="-1" wheel_img="2" wheel_height="${wheel_height}" wheel_radius="${wheel_radius}" >
		<origin xyz="${wheel_offset_x} -${wheel_offset_y} ${wheel_offset_z}" rpy="0 0 0.0"/>
	</xacro:wheel_motor>
	<xacro:wheel_motor parent="robot_body_link" position="front" side="left" reflect="1" wheel_img="2" wheel_height="${wheel_height}" wheel_radius="${wheel_radius}">
		<origin xyz="${wheel_offset_x} ${wheel_offset_y} ${wheel_offset_z}" rpy="0 0 0" />
	</xacro:wheel_motor> 
	<xacro:wheel_motor parent="robot_body_link" position="back" side="left" reflect="1"  wheel_img="1" wheel_height="${wheel_height}" wheel_radius="${wheel_radius}">
		<origin xyz="-${wheel_offset_x} ${wheel_offset_y} ${wheel_offset_z}" rpy="0 0 0" />
	</xacro:wheel_motor>
	<xacro:wheel_motor parent="robot_body_link" position="back" side="right" reflect="-1" wheel_img="1" wheel_height="${wheel_height}" wheel_radius="${wheel_radius}">
		<origin xyz="-${wheel_offset_x} -${wheel_offset_y} ${wheel_offset_z}" rpy="0 0 0" />
	</xacro:wheel_motor>
	
	<xacro:omni_steering />
	<gazebo>
		<!-- <plugin name="gazebo_ros_joint_pose_trajectory"
    	filename="libgazebo_ros_joint_pose_trajectory.so">
			<update_rate>2</update_rate>
		</plugin> -->
		<!-- <plugin name="gazebo_ros_joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
		<update_rate>100</update_rate>
		<joint_name>front_right_wheel_joint</joint_name>
		<joint_name>front_left_wheel_joint</joint_name>
		<joint_name>back_left_wheel_joint</joint_name>
		<joint_name>back_right_wheel_joint</joint_name>
		</plugin> -->
		
	</gazebo>

	<xacro:include filename="sensors/lidar.xacro" />
	<xacro:lidar parent="robot_body_link">
		<origin xyz="0 0 ${body_heigth/2+0.03}" rpy="0 0 0" />
	</xacro:lidar>

	<xacro:include filename="sensors/gps.xacro" />
	<xacro:gps parent="robot_body_link">
		<origin xyz="0 0 0.0"/>
	</xacro:gps>

	<xacro:include filename="sensors/imu.xacro" />
	<xacro:imu parent="robot_body_link">
		<origin xyz="0 0 0.0"/>
	</xacro:imu>

	<xacro:include filename="sensors/camera.xacro" />
	<xacro:camera cam_name="front" parent="robot_body_link">
		<origin xyz="${body_length/2} 0 0.0"/>
	</xacro:camera>

</robot>