apriltag:
  ros__parameters:
    image_transport: raw
    family: Standard41h12
    size: 0.1
    detector:
      threads: 1          # number of threads
      decimate: 2.0       # decimate resolution for quad detection
      blur: 0.0           # sigma of Gaussian blur for quad detection
      refine: true        # snap to strong gradients
      sharpening: 0.25    # sharpening of decoded images
      debug: false        # write additional debugging images to current working directory
# `ros2 pkg prefix follow_me_robot`/share/follow_me_robot/config/apritag.yaml