# --params-file `ros2 pkg prefix follow_me_robot`/share/follow_me_robot/config/sensor_config.yaml
path_builder: # src/follow_me_path_builder/src/path_builder.cpp
  ros__parameters:
    frame:
      map: map # the absolute world frame name
      odom: odom # the odometry frame name
      robot_base: base_link # the robot base frame name
      camera: front_camera_link # the camera frame name
      camera_lense: front_camera_link_optical # the camera lense/sensor frame name
    goal:
      timneout_sec: 60.0 # after this time with no new tag position, the robot will drive to home
    tag:
      family: Standard41h12 # tag family
      id: 0 # tag id to follow
    debug: false # enable debug output
    distance: 0.5 # buffer distance to tag in meters

apriltag: # docs https://github.com/christianrauch/apriltag_ros
  ros__parameters:
    image_transport: raw # image transport format
    family: Standard41h12 # tag family
    size: 0.155 # tag size in meters
    detector: 
      threads: 1       # number of threads
      decimate: 2.0    # decimate resolution for quad detection
      blur: 0.0        # sigma of Gaussian blur for quad detection
      refine: true     # snap to strong gradients
      sharpening: 0.25 # sharpening of decoded images
      debug: false     # write additional debugging images to current working directory
    tags:
      ids: [0] # list of tag ids to detect


teleop: # src/follow_me_teleop/src/teleop.cpp
  ros__parameters:
    joy_topic: /joy
    twist_topic: /cmd_vel
    move:
      forward:
        axis: 1
        scalse: 0.5
        deadzone: 0.5
      reverse:
        axis: 1
        scalse: 0.5
        deadzone: 0.5
      left:
        axis: 0
        scalse: 0.5
        deadzone: 0.5
      right:
        axis: 0
        scale: 0.5
        deadzone: 0.5
    turn:
      left:
        axis: 2
        scalse: 1.0
        deadzone: 0.5
      right:
        axis: 2
        scale: 1.0
        deadzone: 0.5
motor_controller:
  ros__parameters:
    serial:
      port: "/dev/null"
      baudrate: 9600
      timeout: 1.0
    velocity_topic: /cmd_vel